version: "3"
services:
  client:
    image: "docker.io/ztaer/multi-docker-deploy-client:${CLIENT_IMAGE_VERSION}"
    mem_limit: 128m
    hostname: client
    build:
      context: ./client
      dockerfile: Dockerfile
  api:
    image: "docker.io/ztaer/multi-docker-deploy-server:${API_IMAGE_VERSION}"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=${REDIS_HOST} # Redis 服务的主机名
      - REDIS_PORT=${REDIS_PORT} # Redis 服务的端口
      - POSTGRES_USER=${POSTGRES_USER} # PostgreSQL 用户名
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # PostgreSQL 用户密码
      - POSTGRES_HOST=${POSTGRES_HOST} # PostgreSQL 服务的主机名
      - POSTGRES_PORT=${POSTGRES_PORT} # PostgreSQL 服务的端口
      - POSTGRES_DATABASE=${POSTGRES_DATABASE} # PostgreSQL 数据库名
    build:
      context: ./server
      dockerfile: Dockerfile

  worker:
    image: "docker.io/ztaer/multi-docker-deploy-worker:${WORKER_IMAGE_VERSION}"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    build:
      context: ./worker
      dockerfile: Dockerfile

  nginx:
    image: "docker.io/ztaer/multi-docker-deploy-nginx:${NGINX_IMAGE_VERSION}"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
    build:
      context: ./nginx
      dockerfile: Dockerfile
