name: CI and Deploy to AWS Elastic Beanstalk

# 定义触发条件
on:
  push:
    branches:
      - main # 当推送到 main 分支时触发工作流
  pull_request:
    branches:
      - main # 当有 pull request 指向 main 分支时触发工作流
  workflow_dispatch: # 允许手动触发工作流
    branches:
      - main # 指定只针对 main 分支

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新版本的 Ubuntu 作为运行环境
    steps:
      # 步骤 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3 # 检出当前仓库的代码

      # 步骤 2: 登录 Docker Hub
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        # 使用 GitHub Secrets 中存储的 Docker Hub 凭据登录

      # 步骤 3: 构建并测试客户端 Docker 镜像
      - name: Build and Test Client Docker Image
        run: |
          docker build -t ztaer/multi-docker-deployment-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true ztaer/multi-docker-deployment-test npm test
        # 构建客户端 Docker 测试镜像，并运行测试，以确保代码没有破坏

      # 步骤 4: 创建 .env 文件并设置环境变量
      - name: Create .env file from .env.example and set secrets
        run: |
          cp .env.example .env
          sed -i '/^REDIS_HOST=/c\REDIS_HOST=${{ vars.REDIS_HOST }}' .env || echo "REDIS_HOST=${{ vars.REDIS_HOST }}" >> .env 
          sed -i '/^REDIS_PORT=/c\REDIS_PORT=${{ vars.REDIS_PORT }}' .env || echo "REDIS_PORT=${{ vars.REDIS_PORT }}" >> .env
          sed -i '/^POSTGRES_USER=/c\POSTGRES_USER=${{ secrets.POSTGRES_USER }}' .env || echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          sed -i '/^POSTGRES_PASSWORD=/c\POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}' .env || echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          sed -i '/^POSTGRES_HOST=/c\POSTGRES_HOST=${{ vars.POSTGRES_HOST }}' .env || echo "POSTGRES_HOST=${{ vars.POSTGRES_HOST }}" >> .env
          sed -i '/^POSTGRES_PORT=/c\POSTGRES_PORT=${{ vars.POSTGRES_PORT }}' .env || echo "POSTGRES_PORT=${{ vars.POSTGRES_PORT }}" >> .env
          sed -i '/^POSTGRES_DATABASE=/c\POSTGRES_DATABASE=${{ vars.POSTGRES_DATABASE }}' .env || echo "POSTGRES_DATABASE=${{ vars.POSTGRES_DATABASE }}" >> .env
        # 从 .env.example 文件创建 .env 文件，并根据环境变量和秘密更新其中的值

      # 步骤 5: 运行 Docker Compose 并构建镜像和启动容器
      - name: Run Docker Compose with Environment Variables
        run: |
          docker compose -f docker-compose.prod.yml up -d --build
        env:
          REDIS_HOST: ${{vars.REDIS_HOST}} # 设置 Redis 服务的主机名
          REDIS_PORT: ${{vars.REDIS_PORT}} # 设置 Redis 服务的端口
          POSTGRES_USER: ${{secrets.POSTGRES_USER}} # 设置 PostgreSQL 用户名
          POSTGRES_PASSWORD: ${{secrets.DOCKER_PASSWORD}} # 设置 PostgreSQL 用户密码
          POSTGRES_HOST: ${{vars.POSTGRES_HOST}} # 设置 PostgreSQL 服务的主机名
          POSTGRES_PORT: ${{vars.POSTGRES_PORT}} # 设置 PostgreSQL 服务的端口
          POSTGRES_DATABASE: ${{vars.POSTGRES_DATABASE}} # 设置 PostgreSQL 数据库名

      # 步骤 6: 推送 Docker Compose 构建的镜像到 Docker Hub
      - name: Push Docker Compose Images
        run: |
          docker compose push
        # 将通过 Docker Compose 构建的所有镜像推送到 Docker Hub

      # 步骤 7: 生成部署包
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
        # 将项目文件打包为一个 zip 文件，排除 .git 目录

      # 步骤 8: 部署到 AWS Elastic Beanstalk
      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }} # AWS 访问密钥 ID
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS 密钥
          application_name: ${{ vars.AWS_APPLICATION_NAME }} # Elastic Beanstalk 应用名称
          environment_name: ${{ vars.AWS_ENVIRONMENT_NAME }} # Elastic Beanstalk 环境名称
          existing_bucket_name: ${{ vars.AWS_EXISTING_BUCKET_NAME }} # 用于存储部署包的 S3 存储桶
          region: ${{ vars.AWS_REGION }} # 部署的 AWS 区域
          version_label: multi-deploy-${{ github.run_id }} # 部署版本的标签，包含运行编号
          deployment_package: deploy.zip # 部署使用的包文件
          use_existing_version_if_available: true # 如果相同版本存在，使用已存在的版本
        # 使用指定的 AWS 凭据和配置信息，将生成的部署包部署到 AWS Elastic Beanstalk 中
