name: CI and Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main # 触发 CI 的分支
  pull_request:
    branches:
      - main
  workflow_dispatch: # 允许手动触发工作流
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # 指定工作流运行的环境
    steps:
      # 步骤 1: 检查代码，并登录 Docker
      - name: Checkout code
        uses: actions/checkout@v4
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        run: docker build -t ztaer/multi-docker-deployment-test -f ./client/Dockerfile.dev ./client
        run: docker run -e CI=true ztaer/multi-docker-deployment-test npm test

      # 步骤 2: 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -t ztaer/multi-docker-deploy-client ./client
        run: docker build -t ztaer/multi-docker-deploy-server ./server
        run: docker build -t ztaer/multi-docker-deploy-nginx ./nginx
        run: docker build -t ztaer/multi-docker-deploy-worker ./worker
      
      # 步骤 3: 将 Docker 镜像推送到 Docker Hub
      - name: Push Docker image
        run: docker push ztaer/multi-docker-deploy-client
        run: docker push ztaer/multi-docker-deploy-server
        run: docker push ztaer/multi-docker-deploy-nginx
        run: docker push ztaer/multi-docker-deploy-worker
